# Generated by Django 4.1 on 2022-09-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nom_emp'], 'verbose_name': 'Empresas', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='Empresas',
        ),
    ]
