# Generated by Django 4.1 on 2022-09-21 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_tr', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=50, verbose_name='Ingreso - Egreso')),
                ('fecha_tr', models.DateField(auto_now=True)),
                ('concepto', models.TextField(max_length=500, verbose_name='Concepto')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='Users.user')),
            ],
        ),
    ]
