# Generated by Django 4.1 on 2022-09-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Empresas', '0001_initial'),
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nom_emp', models.CharField(max_length=25, verbose_name='Nombres')),
                ('ape_emp', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='Empresas.empresa')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
