# Generated by Django 4.1 on 2022-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nom_usu', models.CharField(max_length=20, unique=True, verbose_name='Nombre Usuario')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('admin', models.BooleanField(null=True, verbose_name='Rol')),
            ],
        ),
    ]
